config/routes.rb
Rails.application.routes.draw do

  root 'home#welcome'

  get '/problems/search_problems', to: 'problems#search_problems', as: :problem_search
  get '/problems/add_contributor', to: 'problems#add_contributor', as: :add_contributor

  get 'problems/filter', to: 'problems#filter_search_results', as: :filter_results

  resources :problems
  resources :problems, only: [:destroy], as: :problem_remove
  devise_for :users, :controllers => { registrations: 'registrations', omniauth_callbacks: 'omniauth_callbacks' }
 
  resources :users, only: [:show, :index, :destroy]
  put 'users/:id', to: 'users#ban'

  resources :comments, only: [:create, :destroy]

  resources :tags, only: [:create, :index, :destroy, :update, :edit]

  resources :professions, only: [:create, :index, :destroy, :update, :edit]

  # for help request mail
  get :send_help_request, to: 'problems#send_help_request', as: :send_help_request

  get '*unmatched_route', to: 'application#not_found'

  if Rails.env.development?
    require 'sidekiq/web'
    mount Sidekiq::Web => '/sidekiq'
  end
end

app/models/profession.rb
class Profession < ApplicationRecord
  validates :name, presence: true, uniqueness: true
  validates :name, length: { in: 1..80 }
  has_many :users
end

app/controllers/professions_controller.rb
class ProfessionsController < ApplicationController
  before_action :authenticate_user!, :authorize_admin

  def index
    @professions = Profession.all
    @profession = Profession.new
  end

  def create
    @professions = Profession.all
    @profession = Profession.new(profession_params)
    @profession.save
  end

  def destroy
    @profession = Profession.find(params[:id])
    @profession.destroy
  end

  def edit
    @profession = Profession.find(params[:id])
  end

  def update
    @profession = Profession.find(params[:id])
    return unless @profession.update(profession_params)
    redirect_to professions_path, notice: 'Profession edited'
  end

  def authorize_admin
    redirect_to root_path, alert: 'Permissions denied' unless
     current_user.is_admin?
  end

  def profession_params
    params.require(:profession).permit(:name)
  end
end

app/views/professions/partials/_form.erb
<div class="new_profession">
  <%= form_for @profession,remote: true, html: { class: 'new-tag-form' } do |f| %>
    <%= f.text_field :name, style:'width:300px;margin: 0 auto;',placeholder: 'Name of profession', class: 'form-control' %>
    <%= f.submit 'Submit', style: 'width:100px;', class: 'btn btn-primary mt-2' %>
  <% end %>
</div>

app/views/professions/partials/_form_errors.erb
<div class='alert alert-danger'>
  <ul>
    <% profession.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
    <% end %>
  </ul>
</div>

app/views/professions/partials/_profession.erb
<div data-profession-id="<%= profession.id %>" class="tab_section2">
  <div class="row mt-3">
    <div class="col">
      <%= profession.name %>
    </div>
    <div class="col">
      <%= link_to 'Delete', profession_path(id: profession.id),remote: true, method: :delete, data: {confirm: "You sure?"}, role: 'button', class: 'btn btn-danger ml-2r' %>
    </div>
    <div class="col">
      <%= link_to 'Edit', edit_profession_path(id: profession.id), method: :get,role: 'button', class: 'btn btn btn-primary' %>
    </div>
  </div>
  <hr/>
</div>