config/routes.rb
Rails.application.routes.draw do

  root 'home#welcome'

  get '/problems/search_problems', to: 'problems#search_problems', as: :problem_search
  get '/problems/add_contributor', to: 'problems#add_contributor', as: :add_contributor

  get 'problems/filter', to: 'problems#filter_search_results', as: :filter_results

  resources :problems
  resources :problems, only: [:destroy], as: :problem_remove
  devise_for :users, :controllers => { registrations: 'registrations', omniauth_callbacks: 'omniauth_callbacks' }
 
  resources :users, only: [:show, :index, :destroy]
  put 'users/:id', to: 'users#ban'

  resources :comments, only: [:create, :destroy]

  resources :tags, only: [:create, :index, :destroy, :update, :edit]

  resources :professions, only: [:create, :index, :destroy, :update, :edit]

  # for help request mail
  get :send_help_request, to: 'problems#send_help_request', as: :send_help_request

  get '*unmatched_route', to: 'application#not_found'

  if Rails.env.development?
    require 'sidekiq/web'
    mount Sidekiq::Web => '/sidekiq'
  end
end

app/models/problem.rb
class Problem < ApplicationRecord
  validates :title, :content, presence: true
  validates :title, length: { in: 5..160 }
  validates :content, length: { in: 5..1500 }
  validate :validate_reference

  belongs_to :creator, class_name: 'User'
  has_many :comments, dependent: :destroy
  has_many :problem_users, inverse_of: :problem
  has_many :users, through: :problem_users, dependent: :destroy
  has_many :problem_tags
  has_many :tags, through: :problem_tags, dependent: :destroy
  accepts_nested_attributes_for :problem_users

  scope :default_search, ->(query) {
    where(
      'lower(title) LIKE ? OR lower(content) LIKE ? OR lower(reference_list) LIKE ?',
      "%#{query}%", "%#{query}%", "%#{query}%"
    )
  }
  scope :tag_where, ->(tag_name) { joins(:tags).merge(Tag.where(name: tag_name)) }
  scope :content_where, ->(query) { where('lower(content) LIKE ?', "%#{query}%") }
  scope :title_where, ->(query) { where('lower(title) LIKE ?', "%#{query}%") }
  scope :reference_where, ->(query) { where('lower(reference_list) LIKE ?', "%#{query}%") }

  scope :order_title_desc, -> { order(title: :desc) }
  scope :order_title_asc, -> { order(title: :asc) }
  scope :order_content_desc, -> { order(content: :desc) }
  scope :order_content_asc, -> { order(content: :asc) }
  scope :updated_at_desc, -> { order(updated_at: :desc) }
  scope :updated_at_asc, -> { order(updated_at: :asc) }

  def current_user_contributor?(user)
    if user.nil?
      false
    elsif users.exists?(id: user.id)
      true
    end
  end

  def creator?(user)
    if user.nil? || creator.nil? || user.id != creator.id
      false
    else
      true
    end
  end

  def validate_reference
    s = reference_list.split(/\n/)
    s.each do |w|
      w.strip!
      array = w.split(' ')
      if array.size == 2 || array.size == 1
        invalid_format unless valid_url?(array[0])
      else
        invalid_format
      end
    end
    # everything ok
  end

  private

  def valid_url?(text)
    regexp = %r{^(http:\/\/www\.|https:\/\/www\.|http:\/\/|https:\/\/)?[a-z0-9]+([\-\.]{1}[a-z0-9]+)*\.[a-z]{2,5}(:[0-9]{1,5})?(\/.*)?$}
    same = text =~ regexp
    return false if same.nil?
    true
  end

  def invalid_format
    errors.add(:reference_list, 'References are not in valid format')
  end
end

app/controllers/problems_controller.rb
class ProblemsController < ApplicationController
  before_action :authenticate_user!, only: %i[new create add_contributor destroy edit update send_help_request]

  def index
    @problems = Problem.all.paginate(per_page: 5, page: params[:page])
  end

  def check_projects
    Gitlab.projects(visibility: 'public', owned: true, simple: true)
  end

  def new
    @problem = Problem.new
    @all_users_mapped = User.all.reject { |user| user == current_user || user.is_admin }
    git = check_projects
    @projects = git.map { |p| [p.path] }
  end

  def edit
    @problem = Problem.find(params[:id])
    is_allowed = @problem.creator_id != current_user.id && !current_user.is_admin
    redirect_to root_path, notice: 'You are not able to edit this problem!' if is_allowed
    @all_users_mapped = User.all.reject { |user| user == current_user || user.is_admin }
    git = Gitlab.projects(visibility: 'public', owned: true, simple: true)
    @projects = git.map { |p| [p.path] }
  end

  def update
    @problem = Problem.find(params[:id])
    if @problem.update(problem_params)
      redirect_to problems_url, notice: 'Problem has been updated'
    else
      render :edit
    end
  end

  def create
    @problem = Problem.new(problem_params.merge(creator_id: current_user.id))
    @all_users_mapped = User.all.reject { |user| user == current_user || user.is_admin }
    git = check_projects
    @projects = git.map { |p| [p.path] }
    if @problem.save
      redirect_to root_path, notice: 'You created post successfully!'
    else
      render :new
    end
  end

  def add_contributor
    @all_users_mapped = User.all.map { |p| [p.full_name, p.id] }
  end

  def search_problems
    begin
      problems_loc = create_searching_service.call
    rescue ArgumentError => e
      redirect_to root_path, alert: e.message
      return
    end
    @problems = problems_loc.paginate(per_page: 5, page: params[:page])
  end

  def filter_search_results
    # we can assume that previous
    # search was successful
    problems_loc = create_searching_service.call
    filtered_results = create_filtering_service(problems_loc).call
    @problems = filtered_results.paginate(per_page: 5, page: params[:page])
    render 'search_problems'
  end

  def show
    @problem = Problem.find(params[:id])
    @comment = Comment.new
    @is_current_contributor = @problem.current_user_contributor?(current_user)
    @is_creator = @problem.creator?(current_user)
    @comments = Comment.where(problem_id: params[:id]).order(created_at: :desc)
    @users = User.all
    @comment_errors = params[:errors] || {}
  end

  def destroy
    @problem = Problem.find(params[:id])
    @problem.destroy
    redirect_to root_path, alert: 'Your problem was successfully destroyed!'
  end

  def send_help_request
    successful = true
    problem = Problem.find(params[:id])
    creator = User.find(problem.creator_id)
    HelpProblemMailer.help_request_email(problem, current_user).deliver_now
    begin
      create_slack_service(
        creator.email,
        problem.title,
        "#{current_user.name} #{current_user.surname}",
        problem_url(id: problem.id)
      ).call
    rescue ArgumentError => e
      flash[:alert] = e.message
      # strange construction
      successful = false
    end
    # change this for more efficient way ?
    redirect_to problem_path(id: params[:id]), notice: 'Email request was sent' unless successful
    redirect_to problem_path(id: params[:id]), notice: 'Request was sent' if successful
  end

  private

  # delegaate this methods to factory class?
  def create_searching_service
    SearchingService.new(
      advanced_search_on: params[:advanced_search_on],
      lookup: params[:lookup],
      title_on: params[:title_on],
      content_on: params[:content_on],
      reference_on: params[:reference_on],
      tag_names: params[:tag_names]
    )
  end

  def create_filtering_service(problems_collection)
    FilteringService.new(
      collection: problems_collection,
      order: params[:order_by]
    )
  end

  def create_slack_service(mail, problem_title, full_name, url)
    SlackService.new(mail, problem_title, full_name, url)
  end

  def problem_params
    params.require(:problem).permit(
      :title,
      :content,
      :reference_list,
      :advanced_search_on,
      :content_on,
      :title_on,
      :status,
      :project,
      tag_ids: [],
      user_ids: [],
      tag_names: [],
      problem_users_attributes: %i[id user_id]
    )
  end
end

app/views/problems/partials/_add_contributor_block.html.erb
<%= fields_for :problem_users, ProblemUser.new  do |problem_form| %>
  <hr />
  <%= problem_form.label :user_id, class: 'form-control mt-2' %>
  <%= problem_form.select :user_id, 
  options_for_select( @all_users_mapped), 
  {}, 
  { 
    class: 'problem_user_partial form-control', 
    name: "problem[problem_users_attributes][][user_id]"
    } 
  %>
<% end %>

app/views/problems/partials/_comment.erb
<div data-comment-id="<%=comment.id %>" class="card card-inner">
  <div class="card-body">
    <div  class="row">
      <div class="col-md-2">
        <%= image_tag(comment.user.avatar.url(:thumb), class: "img img-rounded img-fluid") %>
        <p class="text-secondary text-left"><%= comment.user.full_name%></p>
      </div>
      <div class="col-md-10">
        <p><h5><%= comment.title %></h5></p>
        <p><%= comment.content %></p>
        <hr><p><%= comment.reference_list %></p>
        <p>
        <%if user_signed_in? %>
          <% if current_user.id==comment.user.id || current_user.is_admin?%>
            <%= link_to 'Delete', comment_path(comment.id), method: :delete, remote: true, data: { confirm: 'Are you sure?' }, role: 'button', class: 'float-right btn btn-danger ml-2r' %>
          <% end %>
        <% end %>
        </p>
      </div>
    </div>
  </div>
</div>

app/views/problems/partials/_comment.html.erb
<div data-comment-id="<%=comment.id %>" class="card card-inner">
  <div class="card-body">
    <div  class="row">
      <div class="col-md-2">
        <% # TODO: make it circular %>
        <%= image_tag(comment.user.avatar.url(:thumb), class: "img img-rounded img-fluid") %>
        <p class="text-secondary text-center"><%= comment.user.fullname%></p>
      </div>
      <div class="col-md-10">
        <p>title: <%= comment.title %></p>
        <p>content: <%= comment.content %></p>
        <hr><p>references: <%= comment.references %></p>
        <p>
          <%= link_to 'Delete', comment_path(comment.id), method: :delete, remote: true, data: { confirm: 'Are you sure?' }, role: 'button', class: 'float-right btn btn-danger ml-2r' %>
        </p>
      </div>
    </div>
  </div>
</div>

app/views/problems/partials/_comment_section.erb
<div class="jumbotron">
    <h2 class="text-center">Comment Section</h2>
    <div class="commentSection-comments">
      <% comments.each do |comment| %>
        <%= render 'problems/partials/comment', comment: comment %>
      <% end %>
    </div>
</div>

app/views/problems/partials/_comment_section.html.erb
<div style="background:transparent !important" class="jumbotron">
  <h2 class="text-center">Comment Section</h2>
  
          <div class="container commentSection">
            <% unless comments.nil? %>
              <div class="commentSection-comments">
                <% comments.each do |comment| %>
                  <%= render 'problems/partials/comment', comment: comment %>
                <% end %>
              </div>
            <% end %>
          </div>
   
</div>

app/views/problems/partials/_filter_results.erb
<div class='dropdown show text-right mb-3'>
  <button class="btn btn-info dropdown-toggle" type="button" id="dropdownMenuButton" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
    Filter results
  </button>
  <div class="dropdown-menu" aria-labelledby="dropdownMenuLink">
    <%= link_to 'Title (A-Z)', filter_results_path(order_by: 'title: :asc', advanced_search_on: params[:advanced_search_on], lookup: params[:lookup], title_on: params[:title_on], content_on: params[:content_on], reference_on: params[:reference_on], tag_names: params[:tag_names]), class: 'dropdown-item' %>
    <%= link_to 'Title (Z-A)', filter_results_path(order_by: 'title: :desc', advanced_search_on: params[:advanced_search_on], lookup: params[:lookup], title_on: params[:title_on], content_on: params[:content_on], reference_on: params[:reference_on], tag_names: params[:tag_names]), class: 'dropdown-item' %>
    <%= link_to 'Content (A-Z)', filter_results_path(order_by: 'content: :asc', advanced_search_on: params[:advanced_search_on], lookup: params[:lookup], title_on: params[:title_on], content_on: params[:content_on], reference_on: params[:reference_on], tag_names: params[:tag_names]), class: 'dropdown-item' %>
    <%= link_to 'Content (Z-A)', filter_results_path(order_by: 'content: :desc', advanced_search_on: params[:advanced_search_on], lookup: params[:lookup], title_on: params[:title_on], content_on: params[:content_on], reference_on: params[:reference_on], tag_names: params[:tag_names]), class: 'dropdown-item' %>
    <%= link_to 'From the newest', filter_results_path(order_by: 'updated_at: :desc', advanced_search_on: params[:advanced_search_on], lookup: params[:lookup], title_on: params[:title_on], content_on: params[:content_on], reference_on: params[:reference_on], tag_names: params[:tag_names]), class: 'dropdown-item' %>
    <%= link_to 'From the oldest', filter_results_path(order_by: 'updated_at: :asc', advanced_search_on: params[:advanced_search_on], lookup: params[:lookup], title_on: params[:title_on], content_on: params[:content_on], reference_on: params[:reference_on], tag_names: params[:tag_names]), class: 'dropdown-item' %>
  </div>
</div>

app/views/problems/partials/_form.html.erb
<div class="container">
	<%= bootstrap_form_for @problem, qlabel_errors: true, html: { id: 'new_problem_id', class: 'form-group' } do |f| %>
	  <%= f.text_field :title, placeholder: 'Title', class: 'form-control' %>
	  <%= f.text_area :content, cols: 5, rows: 5, placeholder: 'Content', class: 'form-control' %>
	 	<%= f.text_area :reference_list, cols: 5, rows: 5, placeholder: 'Link Name [ENTER]', class: 'form-control references-js' %>

    <div class="control-group">
      <div class="controls">
        <%= f.select(:project, options_for_select(
        @projects.each_with_index do |element,index|
        [[element[index]],[element[index]]]
      end)) %>
      </div>
    </div>

	 	<%= f.collection_select :tag_ids, Tag.all, :id, :name, { label: "Select tags " }, { multiple: true, class: 'chosen-select'}  %>

    <%= f.collection_select :user_ids, @all_users_mapped, :id, :name,{label: "Select contributors"}, { multiple: true, class: 'chosen-select'} %>

    <hr/>
		<div class="form-check">
				<%= f.check_box :status, label: 'Make my post visible to other users'%>
		</div>

    <br>
	  <%= f.submit 'Save', class: "btn btn-success" %>
	<% end %>
</div>

app/views/problems/partials/_single_result.erb
<div class="problem_single_result">
  <div class="row">
    <div class="col-md-8">
      <div class="card">

        <div class="card-body">
          <h4 class="card-title"><%= problem.title %></h4>
          <% if !problem.creator.nil? %>
            <p class="card-text">Author: <%= link_to "#{problem.creator.name} #{problem.creator.surname}", user_path(id: problem.creator.id ) %> </p>
          <% end %>
          <p class="card-text">Created at: <%= localize(problem.created_at, :format => :long) %> </p>
          <p class='card-text'>Modified at: <%= localize(problem.updated_at, :format => :long) %></p>
          <%= link_to 'Show more information', problem_path(id: problem.id), class: 'btn btn-primary' %>
        </div>
      </div>
    </div>

    <div class="col-md-4">
      <div class="card">
        <div class="card-body">
          <div class="problem_content">
            <%= truncate(problem.content, :length => 250) %>
          </div>
        </div>
      </div>
    </div>

  </div>
</div>