config/routes.rb
Rails.application.routes.draw do

  root 'home#welcome'

  get '/problems/search_problems', to: 'problems#search_problems', as: :problem_search
  get '/problems/add_contributor', to: 'problems#add_contributor', as: :add_contributor

  get 'problems/filter', to: 'problems#filter_search_results', as: :filter_results

  resources :problems
  resources :problems, only: [:destroy], as: :problem_remove
  devise_for :users, :controllers => { registrations: 'registrations', omniauth_callbacks: 'omniauth_callbacks' }
 
  resources :users, only: [:show, :index, :destroy]
  put 'users/:id', to: 'users#ban'

  resources :comments, only: [:create, :destroy]

  resources :tags, only: [:create, :index, :destroy, :update, :edit]

  resources :professions, only: [:create, :index, :destroy, :update, :edit]

  # for help request mail
  get :send_help_request, to: 'problems#send_help_request', as: :send_help_request

  get '*unmatched_route', to: 'application#not_found'

  if Rails.env.development?
    require 'sidekiq/web'
    mount Sidekiq::Web => '/sidekiq'
  end
end

app/models/user.rb
class User < ApplicationRecord
  devise :database_authenticatable, :registerable,
    :recoverable, :rememberable, :trackable, :validatable, :confirmable,
    :omniauthable, omniauth_providers: [:facebook]

  has_attached_file :avatar, styles: { medium: '300x300>', thumb: '100x100>' }

  validates_attachment_content_type :avatar, content_type: %r{\Aimage\/.*\z}
  validates_attachment :avatar, size: { in: 0..3.megabytes }

  validates :name, :surname, presence: true
  validates :name, :surname, length: { in: 3..80 }

  belongs_to :profession, optional: true
  has_many :comments, dependent: :destroy
  has_many :created_problems, foreign_key: :creator_id, class_name: 'Problem', inverse_of: :users
  has_many :problem_users
  has_many :problems, through: :problem_users, dependent: :destroy

  after_create :random_avatar, if: :no_avatar

  def full_name
    "#{name} #{surname}"
  end

  def self.from_omniauth(auth)
    where(provider: auth.provider, uid: auth.uid).first_or_create do |user|
      user.email = auth.info.email
      user.name = auth.info.name.split(' ')[0]
      user.surname = auth.info.name.split(' ')[1]
      user.password = Devise.friendly_token[0, 20]
    end
  end

  private

  # generates default (Gmail-alike) avater
  def random_avatar
    file = Tempfile.new([full_name, '.jpg'])
    file.binmode
    file.write(Avatarly.generate_avatar(name, format: 'jpg', size: 300))
    file.read
    begin
      self.avatar = File.open(file.path)
    ensure
      file.close
      file.unlink
    end
    save
  end

  # checks if avatar was set by user
  def no_avatar
    avatar_file_name.nil?
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authenticate_user!
  before_action :authorize_admin, only: %i[ban destroy]

  def index
    @users = User.all.paginate(per_page: 5, page: params[:page])
  end

  def destroy
    @user = User.find(params[:id])
    @user.destroy
  end

  def edit
    @user = User.find(params[:id])
  end

  def show
    @user = User.find(params[:id])
    user_problems = Problem.where(creator_id: params[:id])
    @problems_posted = user_problems.where(status: true)
    @problems_not_posted = user_problems.where(status: false)
    @user_img = @user.avatar.url(:thumb)
  end

  def ban
    @user = User.find(params[:id])
    if @user.update(user_params)
      redirect_to users_url
    else
      redirect_to users_url, notice: 'Could not perform operation'
    end
  end

  private

  def authorize_admin
    redirect_to root_path, alert: 'Permissions denied' unless
     current_user.is_admin?
  end

  def user_params
    params.require(:user).permit(:blocked)
  end
end

app/views/users/partials/_problems.erb
<% if problems.any? %>
  <% problems.each do |problem| %>
    <div class="row">
      <div class="col-xs-10 col-md-11">
        <div class="card">
          <div class="card-body">
            <h4> <%= link_to problem.title, problem_path(id: problem.id) %> </h4>
            Created at: <%= localize(problem.created_at, :format => :long) %> <br>
          </div>
        </div>
      </div>
    </div>
  <% end %>
<% else %>
  <i>No solutions here </i>
<% end %>

app/views/users/partials/_profile_posts_tabs.erb
<ul class="nav nav-tabs" id="myTab" role="tablist">
  <li class="nav-item">
    <a class="nav-link active" id="home-tab" data-toggle="tab" href="#home" role="tab" aria-controls="home" aria-selected="true">Published</a>
  </li>
  <li class="nav-item">
    <a class="nav-link" id="profile-tab" data-toggle="tab" href="#profile" role="tab" aria-controls="profile" aria-selected="false">Not Published</a>
  </li>
</ul>
<div class="tab-content" id="myTabContent">
  <div class="tab-pane fade show active" id="home" role="tabpanel" aria-labelledby="home-tab">
    <%= render './users/partials/problems', problems: posted %>
  </div>
  <div class="tab-pane fade" id="profile" role="tabpanel" aria-labelledby="profile-tab">
    <%= render './users/partials/problems', problems: not_posted %>
  </div>
</div>

app/views/users/partials/_user.erb
<% unless user.is_admin %>
  <li class="list-group-item" data-user-id =<%= user.id %>>
    <div class="row">
      <div class="col-5">
        <h5> <%= link_to user.email, user_path(id: user.id) %> </h5>
        <%= "#{user.name} #{user.surname}" %><br>

        <% unless user.profession.nil? %>
          <%= user.profession.name %>
        <% end %>
        <br>
      </div>

      <% if current_user.is_admin? %>
        <div class="col-md-4">
          <div class="banned_title">
            <% unless user.blocked.nil? && user.blocked %>
              <% if user.blocked %>
                <br>
                <h3> Banned </h3>
              <% end %>
            <% end %>
          </div>
        </div>

        <div class="col">
          <%= link_to 'Delete', user_path(id: user.id), method: :delete, remote: true, data: {confirm: "You sure?"}, role: 'button', class: 'btn btn-danger ml-2r' %>
            <% if user.blocked %>
              <%= link_to 'Unban', user_path(id: user.id, user: { blocked:false }),controller: :users_controller,action: :update, method: :put, data: {confirm: "You sure?"}, role: 'button', class: 'btn btn-warning ml-2r' %>
            <% else %>
              <%= link_to 'Ban', user_path(id: user.id, user: { blocked:true }),controller: :users_controller,action: :update, method: :put, data: {confirm: "You sure?"}, role: 'button', class: 'btn btn-warning ml-2r' %>
            <% end %>
        </div>
      <% end %>

   </div>

  </li>
  <br>
  <br>
<% end %>