config/routes.rb
Rails.application.routes.draw do

  root 'home#welcome'

  get '/problems/search_problems', to: 'problems#search_problems', as: :problem_search
  get '/problems/add_contributor', to: 'problems#add_contributor', as: :add_contributor

  get 'problems/filter', to: 'problems#filter_search_results', as: :filter_results

  resources :problems
  resources :problems, only: [:destroy], as: :problem_remove
  devise_for :users, :controllers => { registrations: 'registrations', omniauth_callbacks: 'omniauth_callbacks' }
 
  resources :users, only: [:show, :index, :destroy]
  put 'users/:id', to: 'users#ban'

  resources :comments, only: [:create, :destroy]

  resources :tags, only: [:create, :index, :destroy, :update, :edit]

  resources :professions, only: [:create, :index, :destroy, :update, :edit]

  # for help request mail
  get :send_help_request, to: 'problems#send_help_request', as: :send_help_request

  get '*unmatched_route', to: 'application#not_found'

  if Rails.env.development?
    require 'sidekiq/web'
    mount Sidekiq::Web => '/sidekiq'
  end
end

app/views/layouts/partials/_alert.erb
<div class='container flash-js'>
    <% if notice %>
        <div class='alert alert-info'>
          <%= notice %>
        </div>
    <% end %>

    <% if alert %>
        <div class='alert alert-warning'>
             <%= alert %>
        </div>
    <% end %>
</div>

app/views/layouts/partials/_navbar.erb
<nav class="navbar navbar-expand-lg" style='background-color: #271D36;'>
  <%= link_to root_path do  %>
    <%= image_tag 'binarapps_fb_logo.jpg',  size: '60x60'%>
  <% end %>
  <button class="navbar-toggler custom-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="nav navbar-nav navbar-right ml-auto">
      <% if !current_user.nil? %>
        <% if current_user.is_admin == true %>
          <li> <%= link_to 'Tags menu', tags_path, role: 'button', class: 'nav-link mr-3 btn btn-outline-primary form-group' %></li>
          <li> <%= link_to 'Professions menu', professions_path, role: 'button', class: 'nav-link mr-3 btn btn-outline-primary form-group' %></li>
        <% end %>
      <% end %>

      <li> <%= link_to 'All solutions', problems_path, role: 'button', class: 'nav-link mr-3 btn btn-outline-primary form-group' %></li>

      <% if user_signed_in? %>
        <li> <%= link_to 'All users', users_path, role: 'button', class: 'nav-link mr-3 btn btn-outline-primary form-group' %></li>
        <li> <%= link_to current_user.email, user_path(id: current_user.id), role: 'button', class: 'nav-link mr-3 btn btn-outline-warning form-group' %></li>
        <li><%= link_to 'Logout', destroy_user_session_path, role: 'button', method: :delete, class: 'nav-link mr-3  btn btn-outline-warning form-group' %></li>
        <li><%= link_to 'Create a new solution', new_problem_path, role: 'button', class: 'nav-link mr-3 btn btn-outline-success form-group' %></li>
      <% else %>
        <li><%=link_to 'Sign up', new_user_registration_path, role: 'button', class: 'nav-link mr-3 btn btn-outline-warning form-group' %></li>
        <li><%=link_to 'Log in', new_user_session_path, role: 'button', class: 'nav-link mr-3 btn btn-outline-warning form-group' %></li>
      <% end %>
    </ul>
  </div>
</nav>